[workspace]
resolver = "2"
members = [
    "ch01-ownership",
    "ch01-ownership/exercises",
    "ch02-error-handling",
    "ch02-error-handling/exercises",
    "ch03-traits-and-generics",
    "ch03-traits-and-generics/exercises",
    "ch04-content-addressable",
    "ch04-content-addressable/exercises",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
